---

# vim: cursorcolumn cursorline cc=80 ts=2 sw=2 ai

- name: Launch Samba AD domain provision
  shell: >
    samba-tool domain provision
    --realm {{ ad_realm_ok }}
    --domain {{ ad_domain_ok }}
    --adminpass "{{ ad_admin_pass }}"
    --server-role=dc
    --use-rfc2307
    --host-ip={{ ad_ipv4 }}
    --host-ip6={{ ad_ipv6 }}
    --option="dns forwarder = {{ ansible_dns.nameservers[0] }}"
  register: samba-provision-log

- name: Link krb5 configuration
  file:
    src: /var/lib/samba/private/krb5.conf
    dest: /etc/krb5.conf
    state: link
  notify:
    - restart samba

